spring.application.name=auth-service

# ===============================
# SERVER CONFIG
# ===============================
server.port=8080

# ===============================
# DATABASE (POSTGRESQL)
# ===============================
spring.datasource.url=jdbc:postgresql://localhost:5432/finflow
spring.datasource.username=postgres
spring.datasource.password=root

spring.datasource.driver-class-name=org.postgresql.Driver

# ===============================
# JPA / HIBERNATE
# ===============================
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# ===============================
# JWT CONFIG
# ===============================
jwt.secret=mysupersecretkeymysupersecretkey
jwt.expiration=86400000

# ===============================
# EUREKA
# ===============================
eureka.client.service-url.defaultZone=http://localhost:8761/eureka
eureka.client.register-with-eureka=false
eureka.client.fetch-registry=false