sonar.projectKey=fin-flow
sonar.projectName=FinFlow Loan Management System
sonar.projectVersion=1.0

sonar.sources=auth-service/src/main/java,application-service/src/main/java,document-service/src/main/java,admin-service/src/main/java,api-gateway/src/main/java,config-server/src/main/java,eureka-server/src/main/java
sonar.tests=auth-service/src/test/java,application-service/src/test/java,document-service/src/test/java,admin-service/src/test/java,api-gateway/src/test/java,config-server/src/test/java,eureka-server/src/test/java
sonar.java.binaries=auth-service/target/classes,application-service/target/classes,document-service/target/classes,admin-service/target/classes,api-gateway/target/classes,config-server/target/classes,eureka-server/target/classes
sonar.java.test.binaries=auth-service/target/test-classes,application-service/target/test-classes,document-service/target/test-classes,admin-service/target/test-classes,api-gateway/target/test-classes,config-server/target/test-classes,eureka-server/target/test-classes
sonar.coverage.jacoco.xmlReportPaths=auth-service/target/site/jacoco/jacoco.xml,application-service/target/site/jacoco/jacoco.xml,document-service/target/site/jacoco/jacoco.xml,admin-service/target/site/jacoco/jacoco.xml,api-gateway/target/site/jacoco/jacoco.xml,config-server/target/site/jacoco/jacoco.xml,eureka-server/target/site/jacoco/jacoco.xml

sonar.sourceEncoding=UTF-8
sonar.exclusions=**/target/**,**/node_modules/**,**/dist/**,**/.angular/**,**/.sonarlint/**,**/.metadata/**
sonar.test.exclusions=**/target/**
sonar.coverage.exclusions=**/*Application.java,**/config/**,**/dto/**,**/entity/**
sonar.cpd.exclusions=**/config/**,**/dto/**,**/entity/**
